# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.


  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/7"

  config.vm.provision "shell", inline: <<-SHELL
   sudo su

   # user ansible
   groupadd -g 9999 ansible
   useradd -m -s /bin/bash ansible -u 9999 -g ansible
   echo "%ansible ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/ansible
   echo -e "ansible\nansible" | (passwd ansible)
   cp /etc/ssh/sshd_config /etc/ssh/ori_sshd_config
   sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
   service sshd restart

  SHELL

  config.vm.provision "ansible" do |ansible|
   ansible.playbook = "/etc/ansible/roles/vagrant/vagrant_fqdn.yml"
  end

  # Default size is 40 GO
  #config.disksize.size = "60GB"
  
  ### Semantiweb
  
  config.vm.define "dadm" do |adm|
   adm.vm.hostname = "dadm"
   #adm.vm.network "private_network", ip: "192.168.0.170"
   config.vm.network "public_network", :bridge => "wlp2s0 : wifi", :ip => "192.168.0.170"
   adm.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "4096"]
          #vb.customize ["modifyvm", :id, "--cpus", "2"]
   end

  end

  config.vm.define "dwk1" do |wk|
   wk.vm.hostname = "dwk1"
   #wk.vm.network "private_network", ip: "192.168.0.171"
   config.vm.network "public_network", :bridge => "wlp2s0 : wifi", :ip => "192.168.0.171"
   wk.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "4096"]
          #vb.customize ["modifyvm", :id, "--cpus", "1"]
   end
  end

  config.vm.define "dwk2" do |wk2|
   wk2.vm.hostname = "dwk2"
   #wk2.vm.network "private_network", ip: "192.168.0.172"
   config.vm.network "public_network", :bridge => "wlp2s0 : wifi", :ip => "192.168.0.172"
   wk2.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "4096"]
          #vb.customize ["modifyvm", :id, "--cpus", "1"]
   end
  end

end
